<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="preload" href="http://localhost:1313/fonts/vendor/jost/jost-v4-latin-regular.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="http://localhost:1313/fonts/vendor/jost/jost-v4-latin-500.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="http://localhost:1313/fonts/vendor/jost/jost-v4-latin-700.woff2" as="font" type="font/woff2" crossorigin>
<script 
  src="/js/color-mode.f14b3e296de1d0b69e75af684b62a4a912a2cadab04e36123407cd8388204f1d.js"
  integrity="sha256-8Us&#43;KW3h0Laeda9oS2KkqRKiytqwTjYSNAfNg4ggTx0=">
</script>


<link rel="stylesheet" href="/main.33758d2c063fdb6977b91f609c2e676c70b30831326d76dca2350eb7601945d813a377425cd5279dc2dec5656893b0a29be880ea7efd7787043b134a3bbb9dec.css" integrity="sha512-M3WNLAY/22l3uR9gnC5nbHCzCDEybXbcojUOt2AZRdgTo3dCXNUnncLexWVok7Cim&#43;iA6n79d4cEOxNKO7ud7A==" crossorigin="anonymous">

<noscript><style>img.lazyload { display: none; }</style></noscript><base href="http://localhost:1313/_solidworks-macros/001.4-select-plane-from-tree/">

  <link rel="canonical" href="http://localhost:1313/_solidworks-macros/001.4-select-plane-from-tree/">


<title>Solidworks Macro - Selection Methods  |  The CAD Coder</title>
<meta name="description" content="Automate CAD with powerful macros and tools!">

    
    <link rel="icon" href="/favicon.ico" sizes="32x32">
    
      <link rel="icon" href="/favicon.svg" type="image/svg+xml">
    
      <link
        rel="apple-touch-icon"
        href="/apple-touch-icon.png"
        sizes="180x180"
        type="image/png"
      >
      <link
        rel="icon"
        href="/favicon-192x192.png"
        sizes="192x192"
        type="image/png"
      >
      <link
        rel="icon"
        href="/favicon-512x512.png"
        sizes="512x512"
        type="image/png"
      >
<link rel="manifest" href="/manifest.webmanifest">

<meta property="og:url" content="http://localhost:1313/_solidworks-macros/001.4-select-plane-from-tree/">
  <meta property="og:site_name" content="The CAD Coder">
  <meta property="og:title" content="Solidworks Macro - Selection Methods">
  <meta property="og:description" content="In this post, we select Default planes with following methods:
By SelectByID method From ModelDoc2 Interface
By SelectByID2 method From IModelDocExtension Interface">
  <meta property="og:locale" content="en">
  <meta property="og:type" content="article">
    <meta property="article:section" content="_solidworks-macros">
    <meta property="article:tag" content="Solidworks Macro">
    <meta property="og:image" content="http://localhost:1313/logo.png">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:image" content="http://localhost:1313/logo.png">
  <meta name="twitter:title" content="Solidworks Macro - Selection Methods">
  <meta name="twitter:description" content="In this post, we select Default planes with following methods:
By SelectByID method From ModelDoc2 Interface
By SelectByID2 method From IModelDocExtension Interface">

    
    <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "BreadcrumbList",
   "itemListElement": [
     {
       "@type": "ListItem",
       "item": "http://localhost:1313/",
       "name": "The Cad Coder",
       "position": 1
     },
     {
       "@type": "ListItem",
       "item": "http://localhost:1313/_solidworks-macros/",
       "name": "Solidworks Macros",
       "position": 2
     },
     {
       "@type": "ListItem",
       "name": "Solidworks Macro Selection Methods",
       "position": 3
     }
   ]
 }
</script>





<script>
  (function (w, d, e, u, f, l, n) {
    w[f] = w[f] || function () {
      (w[f].q = w[f].q || [])
        .push(arguments);
    }, l = d.createElement(e), l.async = 1, l.src = u,
      n = d.getElementsByTagName(e)[0], n.parentNode.insertBefore(l, n);
  })
    (window, document, 'script', 'https://assets.mailerlite.com/js/universal.js', 'ml');
  ml('account', '1644816');
</script>

</head>

  
  <body class="single section _solidworks-macros" data-bs-spy="scroll" data-bs-target="#toc" data-bs-root-margin="0px 0px -60%" data-bs-smooth-scroll="true" tabindex="0">
    <div class="sticky-top">
<header class="navbar navbar-expand-lg">
  <div class="container-fluid">
  
    <a class="navbar-brand me-auto me-lg-3" href="/">The CAD Coder</a>

    
    
    <button type="button" id="searchToggleMobile" class="btn btn-link nav-link mx-2 d-lg-none" aria-label="Search website">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-search" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <circle cx="10" cy="10" r="7"></circle>
        <line x1="21" y1="21" x2="15" y2="15"></line>
      </svg>
    </button>
    
    
    <button class="btn btn-link nav-link mx-2 order-3 d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavMain" aria-controls="offcanvasNavMain" aria-label="Open main navigation menu">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-menu" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <line x1="4" y1="8" x2="20" y2="8"></line>
        <line x1="4" y1="16" x2="20" y2="16"></line>
      </svg>
    </button>

    
    <div class="offcanvas offcanvas-end h-auto" tabindex="-1" id="offcanvasNavMain" aria-labelledby="offcanvasNavMainLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavMainLabel">The CAD Coder</h5>
        <button type="button" class="btn btn-link nav-link p-0 ms-auto" data-bs-dismiss="offcanvas" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M18 6l-12 12"></path>
            <path d="M6 6l12 12"></path>
         </svg>
        </button>
      </div>
      
      <div class="offcanvas-body d-flex flex-column flex-lg-row justify-content-between">
        <ul class="navbar-nav flex-grow-1"><li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/knowledge-base/">Knowledge Base</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/vba/vba-introduction/">VBA</a>
              </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Solidworks<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M6 9l6 6l6 -6"></path>
                  </svg>
                </a>
                <ul class="dropdown-menu shadow rounded border-0">
                  <li><a class="dropdown-item" href="http://localhost:1313/solidworks/solidworks-vba-macro/">Solidworks VBA Macro</a></li>
                  <li><a class="dropdown-item" href="http://localhost:1313/solidworks-csharp-api/">Solidworks C# API</a></li>
                  <li><a class="dropdown-item" href="http://localhost:1313/solidworks-cpp-api/">Solidworks C&#43;&#43; API</a></li>
                  </ul>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/wpf-tutorials/syncfusion-account-signup/">WPF Tutorials</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/knowledge-base/wix4-introduction/">Wix4 Tutorials</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/resources/">Resources</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost:1313/aboutme/">About</a>
              </li>
            </ul>

        
        
        <button type="button" id="searchToggleDesktop" class="btn btn-link nav-link p-2 d-none d-lg-block" aria-label="Search website">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-search" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <circle cx="10" cy="10" r="7"></circle>
            <line x1="21" y1="21" x2="15" y2="15"></line>
          </svg>
        </button>
        
        
        
        <button id="buttonColorMode" class="btn btn-link mx-auto nav-link p-0 ms-lg-2 me-lg-1" type="button" aria-label="Toggle theme">
          <svg data-bs-theme-value="dark" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-moon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"></path>
          </svg>
          <svg data-bs-theme-value="light" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-sun" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0m-5 0h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path>
          </svg>
        </button>
        
        <ul id="socialMenu" class="nav mx-auto flex-row order-lg-4">
          <li class="nav-item">
              <a class="nav-link social-link" href="https://www.linkedin.com/in/prashantbaher/"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-linkedin" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M6 20v-10h4v10h-4z"></path><path d="M14 20v-5c0 -1.5 .5 -3.5 3 -3.5s3.5 2.5 3.5 4.5v4h-4v-3c0 -1.5 -.5 -2.5 -1.5 -2.5s-1.5 .5 -1.5 2v3h-4z"></path></svg><small class="ms-2 visually-hidden">LinkedIn</small></a>
            </li>
          <li class="nav-item">
              <a class="nav-link social-link" href="https://www.facebook.com/TheCadCoder"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-facebook" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M7 10v4h3v7h4v-7h3l1-4h-4v-2a1 1 0 0 1 1-1h3v-4h-3a5 5 0 0 0-5 5v2h-3"></path></svg><small class="ms-2 visually-hidden">Facebook</small></a>
            </li>
          <li class="nav-item">
              <a class="nav-link social-link" href="https://www.youtube.com/@TheCadCoder"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="currentColor"><path d="M31.67 8.87a4 4 0 0 0-2.82-2.83C26.13 5.33 16 5.33 16 5.33s-10.13 0-12.85.71A4 4 0 0 0 .33 8.87 41.13 41.13 0 0 0 0 16a41.13 41.13 0 0 0 .33 7.13 4 4 0 0 0 2.82 2.83c2.72.71 12.85.71 12.85.71s10.13 0 12.85-.71a4 4 0 0 0 2.82-2.83A41.13 41.13 0 0 0 32 16a41.13 41.13 0 0 0-.33-7.13zM12.8 21.2V10.8l8.53 5.2z"/></svg><small class="ms-2 visually-hidden">YouTube</small></a>
            </li>
          </ul>
        
        </div>
    </div>

    
    </div>
</header>
</div>

<div class="modal" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-fullscreen-md-down">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 visually-hidden" id="searchModalLabel">Search</h1>
        <button type="button" class="btn-close visually-hidden" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="search-input flex-grow-1 d-none">
          <form id="search-form" class="search-form" action="#" method="post" accept-charset="UTF-8" role="search">
            <label for="query" class="visually-hidden">Search</label>
            <div class="d-flex">
              <input type="search" id="query" name="query" class="search-text form-control form-control-lg" placeholder="Search" aria-label="Search" maxlength="128" autocomplete="off">
              <button type="button" class="btn btn-link text-decoration-none px-0 ms-3 d-md-none" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-body">
        <p class="search-loading status message d-none mt-3 text-center">Loading search index‚Ä¶</p>
        <p class="search-no-recent message d-none mt-3 text-center">No recent searches</p>
        <p class="search-no-results message d-none mt-3 text-center">No results for "<strong><span class="query-no-results">Query here</span></strong>"</p>
        <div id="searchResults" class="search-results"></div>
        <template>
          <article class="search-result list-view">
            <div class="card my-3">
              <div class="card-body">
                <header>
                  <h2 class="h5 title title-submitted mb-0"><a class="stretched-link text-decoration-none text-reset" href="#">Title here</a></h2>
                  <div class="submitted d-none"><time class="created-date">Date here</time></div>
                </header>
                <div class="content">Summary here</div>
              </div>
            </div>
          </article>
        </template>
      </div>
      <div class="modal-footer">
        <ul class="list-inline me-auto d-none d-md-block">
          <li class="list-inline-item"><kbd class="me-2"><svg width="15" height="15" aria-label="Enter key" role="img"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2"><path d="M12 3.53088v3c0 1-1 2-2 2H4M7 11.53088l-3-3 3-3"></path></g></svg></kbd><span class="DocSearch-Label">to select</span></li>
          <li class="list-inline-item"><kbd class="me-2"><svg width="15" height="15" aria-label="Arrow down" role="img"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2"><path d="M7.5 3.5v8M10.5 8.5l-3 3-3-3"></path></g></svg></kbd><kbd class="me-2"><svg width="15" height="15" aria-label="Arrow up" role="img"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2"><path d="M7.5 11.5v-8M10.5 6.5l-3-3-3 3"></path></g></svg></kbd><span class="DocSearch-Label">to navigate</span></li>
          <li class="list-inline-item"><kbd class="me-2"><svg width="15" height="15" aria-label="Escape key" role="img"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2"><path d="M13.6167 8.936c-.1065.3583-.6883.962-1.4875.962-.7993 0-1.653-.9165-1.653-2.1258v-.5678c0-1.2548.7896-2.1016 1.653-2.1016.8634 0 1.3601.4778 1.4875 1.0724M9 6c-.1352-.4735-.7506-.9219-1.46-.8972-.7092.0246-1.344.57-1.344 1.2166s.4198.8812 1.3445.9805C8.465 7.3992 8.968 7.9337 9 8.5c.032.5663-.454 1.398-1.4595 1.398C6.6593 9.898 6 9 5.963 8.4851m-1.4748.5368c-.2635.5941-.8099.876-1.5443.876s-1.7073-.6248-1.7073-2.204v-.4603c0-1.0416.721-2.131 1.7073-2.131.9864 0 1.6425 1.031 1.5443 2.2492h-2.956"></path></g></svg></kbd><span class="DocSearch-Label">to close</span></li>
        </ul>
        <p class="d-md-none">Search by <a class="text-decoration-none" href="https://github.com/nextapps-de/flexsearch">FlexSearch</a></p>
      </div>
    </div>
  </div>
</div>


    <div class="wrap container-fluid" role="document">
      <div class="content">
      <div class="container p-0">
        
	<div class="row flex-xl-nowrap">
		
		<nav class="docs-toc d-none d-xl-block col-xl-3" aria-label="Secondary navigation">
			<div class="page-links">
  <h3>On this page</h3>
    <nav id="toc">
  <ul>
    <li><a href="#by-selectbyid-method-from-modeldoc2-interface">By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface</a>
      <ul>
        <li><a href="#using-selectbyid-method-in-previous-example">Using SelectByID method in previous example</a></li>
        <li><a href="#using-selectbyid-method-in-an-open-document">Using SelectByID method in an Open document</a></li>
      </ul>
    </li>
    <li><a href="#by-selectbyid2-method-from-imodeldocextension-interface">By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface</a>
      <ul>
        <li><a href="#using-selectbyid2-method-in-previous-example">Using SelectByID2 method in previous example</a></li>
        <li><a href="#using-selectbyid2-method-in-an-open-document">Using SelectByID2 method in an Open document</a></li>
      </ul>
    </li>
  </ul>
</nav>
</div>

		</nav>
		<main class="docs-content col-lg-11 col-xl-9 mx-xl-auto">
		
			<h1>Solidworks Macro - Selection Methods</h1>
			
			<nav class="toc-mobile d-xl-none" aria-label="Quaternary navigation">
				<details>
    <summary>On this page</summary>
    <div class="page-links">
      <nav id="TableOfContents">
  <ul>
    <li><a href="#by-selectbyid-method-from-modeldoc2-interface">By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface</a>
      <ul>
        <li><a href="#using-selectbyid-method-in-previous-example">Using SelectByID method in previous example</a></li>
        <li><a href="#using-selectbyid-method-in-an-open-document">Using SelectByID method in an Open document</a></li>
      </ul>
    </li>
    <li><a href="#by-selectbyid2-method-from-imodeldocextension-interface">By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface</a>
      <ul>
        <li><a href="#using-selectbyid2-method-in-previous-example">Using SelectByID2 method in previous example</a></li>
        <li><a href="#using-selectbyid2-method-in-an-open-document">Using SelectByID2 method in an Open document</a></li>
      </ul>
    </li>
  </ul>
</nav>
    </div>
  </details>

			</nav>
			<p>In this post, we select <strong>Default planes</strong> with following methods:</p>
<ol>
<li>
<p>By <code>SelectByID</code> method From <code>ModelDoc2</code> Interface</p>
</li>
<li>
<p>By <code>SelectByID2</code> method From <code>IModelDocExtension</code> Interface</p>
</li>
</ol>
<h2 id="by-selectbyid-method-from-modeldoc2-interface">By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface<a href="#by-selectbyid-method-from-modeldoc2-interface" class="anchor" aria-hidden="true">#</a> </h2>
<p><code>SelectByID</code> method From <code>ModelDoc2</code> Interface is the easiest method for selecting Default plane.</p>
<p>I will explain the use of this method in 2 different scenerio as follows:</p>
<ol>
<li>
<p>Using this method in the previous example of creating a new document and then select a Plane.</p>
</li>
<li>
<p>Using this method in an open document.</p>
</li>
</ol>
<h3 id="using-selectbyid-method-in-previous-example">Using SelectByID method in previous example<a href="#using-selectbyid-method-in-previous-example" class="anchor" aria-hidden="true">#</a> </h3>
<p>In the previous 2 posts, we learned how to create <em>a new part document, an assembly document, and a drawing document</em>.</p>
<p>Now we use the same code and <em>extended</em> it for using selecting planes.</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="k">Option</span> <span class="n">Explicit</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks document
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Boolean Variable
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Main function of our VBA program
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks variable to Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl">    
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Creating string type variable for storing default part location
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Dim</span> <span class="n">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting value of this string type variable to &#34;Default part template&#34;
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks document to new part document
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">End</span> <span class="k">Sub</span></span></span></code></pre></div>
  </figure>
</div>
<p>Above code, 1st create a new part document and then select &ldquo;<strong>Front Plane</strong>&rdquo; in VBA macro.</p>
<p>To select the plane, I have to add 2 lines. 1st I create a boolean varible above main function as shown in below code:</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="c">&#39; Boolean Variable
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span></span></span></code></pre></div>
  </figure>
</div>
<p>Then I use this <code>BoolStatus</code> variable to selecting <em>Front Plane</em> as shown in below code:</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">)</span></span></span></code></pre></div>
  </figure>
</div>
<p><code>SelectByID</code> takes following parameters:</p>
<ul>
<li>
<p><em>Name</em> : Name of the object or an empty string</p>
</li>
<li>
<p><em>Type</em> : Type of object in uppercase or an empty string</p>
</li>
<li>
<p><em>X</em> : X selection location</p>
</li>
<li>
<p><em>Y</em> : Y selection location</p>
</li>
<li>
<p><em>Z</em> : Z selection location</p>
</li>
</ul>
<p><strong>Return Value</strong> -</p>
<p>If the item is select then this method returns <code>True</code> and otherwise <code>False</code>.</p>
<p>Since this method returns <code>True</code> or <code>False</code>, hence we use a <code>boolean</code> variable to perfom this method.</p>
<p>If we want to select <strong>Right Plane</strong> then we just need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Right Plane&quot;</code> in previous code sample.</p>
<p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Top Plane&quot;</code> in previous code sample.</p>
<h3 id="using-selectbyid-method-in-an-open-document">Using SelectByID method in an Open document<a href="#using-selectbyid-method-in-an-open-document" class="anchor" aria-hidden="true">#</a> </h3>
<p>For using <code>SelectByID</code> method in an open document we use differnet code sample.</p>
<p>The code sample is given below:</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="k">Option</span> <span class="n">Explicit</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks document
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Boolean Variable
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Main function of our VBA program
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks variable to Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl">        
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks document to active open document
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
</span></span><span class="line"><span class="cl">        
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">End</span> <span class="k">Sub</span></span></span></code></pre></div>
  </figure>
</div>
<p>Most of the things in this code sample is already explained <strong><a href="/solidworks-macros/open-new-document">previous post</a></strong> and in previous section of this very post.</p>
<p>In this code I have set the <em>Solidworks document variable</em> <code>swDoc</code> to active open document.</p>
<p>And then we use similar method to select <strong>&ldquo;Front Plane&rdquo;</strong>.</p>
<p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p>
<hr>
<h2 id="by-selectbyid2-method-from-imodeldocextension-interface">By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface<a href="#by-selectbyid2-method-from-imodeldocextension-interface" class="anchor" aria-hidden="true">#</a> </h2>
<p>This method is similar to <code>SelectByID</code> from previous section infact it is the <em>updated version</em> of previous method.</p>
<p>Since it is <em>updated</em> and has <em>additional functionality</em>, I will explain it I <em><strong>frequently</strong></em> use this method. Previous method is easiest method, by far, for selecting objects.</p>
<p>Since <code>SelectByID2</code> is updated version of <code>SelectByID</code> it has similar syntax and usage.</p>
<p>I will explain the use of <code>SelectByID2</code> method in 2 different scenerio as done in previous method:</p>
<ol>
<li>
<p>Using this method in the previous example of creating a new document and then select a Plane.</p>
</li>
<li>
<p>Using this method in an open document.</p>
</li>
</ol>
<h3 id="using-selectbyid2-method-in-previous-example">Using SelectByID2 method in previous example<a href="#using-selectbyid2-method-in-previous-example" class="anchor" aria-hidden="true">#</a> </h3>
<p>Now we use the same code and <em>extended</em> it for using selecting planes by <code>SelectByID2</code> method.</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="k">Option</span> <span class="n">Explicit</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks document
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Boolean Variable
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Main function of our VBA program
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks variable to Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl">    
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Creating string type variable for storing default part location
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Dim</span> <span class="n">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting value of this string type variable to &#34;Default part template&#34;
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks document to new part document
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">End</span> <span class="k">Sub</span></span></span></code></pre></div>
  </figure>
</div>
<p>This method is doing the <em>same thing</em> which I already explained in the previous method.</p>
<p>The difference is in the <em>syntax</em> and <em>input parameters</em>.</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span></span></span></code></pre></div>
  </figure>
</div>
<p>As you can see from the above code sample, this method is a method of <code>Extension</code> interface/object.</p>
<p>This <code>Extension</code> interface/object is part of <code>swDoc</code> variable. This variable is the type of <code>ModelDoc2</code> interface/object.</p>
<p>Apart from that, we need to give additional input parameters also.</p>
<p>Below I have explained about the input parameters of <code>SelectByID2</code> method:</p>
<ul>
<li>
<p><em>Name</em> : Name of the object or an empty string</p>
</li>
<li>
<p><em>Type</em> : Type of object in uppercase or an empty string</p>
</li>
<li>
<p><em>X</em> : X selection location</p>
</li>
<li>
<p><em>Y</em> : Y selection location</p>
</li>
<li>
<p><em>Z</em> : Z selection location</p>
</li>
<li>
<p><em>Append</em> : <code>True</code> or <code>False</code>. It is used the adding the selection into selection list.</p>
</li>
<li>
<p><em>Mark</em> : Value you want to use as a Mark; this value is used by other functions that require ordered selection.</p>
</li>
<li>
<p><em>Callout</em> : Pointer to the <code>Callout</code> interface/object. (Default value most of the time is <code>nothing</code>.)</p>
</li>
<li>
<p><em>SelectOption</em> : Selection option. You can use either <code>swSelectOptionDefault</code> or <code>swSelectOptionExtensive</code> value.</p>
</li>
</ul>
<p><strong>Return Value</strong> -</p>
<p>If the item is select then this method returns <code>True</code> and otherwise <code>False</code>.</p>
<p>There is <strong>a lot more</strong> about this method in the <em><strong>Remark</strong></em> section. For more information visit <a href="http://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imodeldocextension~selectbyid2.html">here</a>.</p>
<p>Since this method returns <code>True</code> or <code>False</code>, here also we use a <code>boolean</code> variable to perfom this method.</p>
<p>If we want to select <strong>Right Plane</strong> then we just need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Right Plane&quot;</code> in previous code sample.</p>
<p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Top Plane&quot;</code> in previous code sample.</p>
<h3 id="using-selectbyid2-method-in-an-open-document">Using SelectByID2 method in an Open document<a href="#using-selectbyid2-method-in-an-open-document" class="anchor" aria-hidden="true">#</a> </h3>
<p>For using <code>SelectByID2</code> method in an open document we use same code sample as used in previous method.</p>
<p>The code sample is given below:</p>



<div class="expressive-code">
  <figure class="frame not-content">
  <figcaption class="header">
    <span class="title"></span>
  </figcaption>
  <div class="highlight"><pre tabindex="0" class="chroma"><code class="language-vb" data-lang="vb"><span class="line"><span class="cl"><span class="k">Option</span> <span class="n">Explicit</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Creating variable for Solidworks document
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</span></span><span class="line"><span class="cl"><span class="c">&#39; Boolean Variable
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Dim</span> <span class="n">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="c">&#39; Main function of our VBA program
</span></span></span><span class="line"><span class="cl"><span class="c"></span><span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks variable to Solidworks application
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</span></span><span class="line"><span class="cl">        
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Setting Solidworks document to active open document
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
</span></span><span class="line"><span class="cl">        
</span></span><span class="line"><span class="cl">    <span class="c">&#39; Selecting Front Plane
</span></span></span><span class="line"><span class="cl"><span class="c"></span>    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">&#34;Front Plane&#34;</span><span class="p">,</span> <span class="s">&#34;PLANE&#34;</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="n">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">End</span> <span class="k">Sub</span></span></span></code></pre></div>
  </figure>
</div>
<p>Most of the things in this code sample is already explained <strong><a href="/solidworks-macros/open-new-document">previous post</a></strong> and in previous section of this very post.</p>
<p>In this code I have set the <em>Solidworks document variable</em> <code>swDoc</code> to active open document.</p>
<p>And then we use similar method to select <strong>&ldquo;Front Plane&rdquo;</strong>.</p>
<p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p>
<p>This is all for now. This post is getting too long.</p>
<p>In next post we learn about <em><strong>Open Saved Documents</strong></em>.</p>
<ul>
<li><a href="/download-solidworks-macros/">üéÅ Download 5 Free SolidWorks Macros ‚Üí</a></li>
</ul>

			<div class="page-footer-meta d-flex flex-column flex-md-row justify-content-between">
				</div>
			<div class="page-nav d-flex flex-column flex-sm-row">
	
	<div class="card w-100">
			<div class="card-body d-flex">
				<div class="d-flex flex-column justify-content-center">
					<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-left" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
						<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
						<path d="M5 12l14 0"></path>
						<path d="M5 12l6 6"></path>
						<path d="M5 12l6 -6"></path>
				 	</svg>
				</div>
				<div class="d-flex flex-column">
					<div class="text-body-secondary">Prev</div>
					<a href="/_solidworks-macros/012.2-rotate-copy-sketch-entities/" class="stretched-link text-reset text-decoration-none">Solidworks Macro - Rotate/Copy Sketch Entities</a>
				</div>
			</div>
		</div>
	<div class="m-2"></div>
	<div class="card text-end w-100">
			<div class="card-body d-flex justify-content-end">
				<div class="d-flex flex-column">
					<div class="text-body-secondary">Next</div>
					<a href="/_solidworks-macros/099.2-split-sketch-segments/" class="stretched-link text-reset text-decoration-none">Solidworks Macro - Split Open/Closed Sketch Entities</a>
				</div>
				<div class="d-flex flex-column justify-content-center">
					<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-right" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
						<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
						<path d="M5 12l14 0"></path>
						<path d="M13 18l6 -6"></path>
						<path d="M13 6l6 6"></path>
					</svg>
				</div>
			</div>
		</div>
	</div>

			
		</main>
		
	</div>

      </div>
      </div>
    </div>
    
    
    <footer class="footer text-muted">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 text-center text-lg-start">
        <ul class="list-inline">
          <li class="list-inline-item"><a class="text-muted" href="/privacy/">Privacy Policy</a></li>
        </ul>
      </div>
      <div class="col-lg-8 text-center text-lg-end">
        <ul class="list-inline">
          <li class="list-inline-item">Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

    

<script async
  src="/js/app.2369991ae7670dc0c533c0a66142f2e8025973140211517495657e96c516ffde.js"
  integrity="sha256-I2mZGudnDcDFM8CmYULy6AJZcxQCEVF0lWV&#43;lsUW/94=">
</script>





<script async
  src="/js/flexsearch.8350d2f520e131f8552ed57c1eadd05c50eccf0427267781442dd8ddf8fdcdf7.js"
  integrity="sha256-g1DS9SDhMfhVLtV8Hq3QXFDszwQnJneBRC3Y3fj9zfc=">
</script>
<script async
  src="/js/search-modal.877cece5b6bc789456f89fa1955ccfcd8a5acdb2179e7882e292a6caa49efe68.js"
  integrity="sha256-h3zs5ba8eJRW&#43;J&#43;hlVzPzYpazbIXnniC4pKmyqSe/mg=">
</script>

    
  </body>
</html>