<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>General - Functions on The CAD Coder</title>
    <link>http://localhost:1313/solidworks-macros/01-general---solidworks-functions/</link>
    <description>Recent content in General - Functions on The CAD Coder</description>
    <generator>Hugo</generator>
    <language>en</language>
    <copyright>Copyright (c) The CAD Coder</copyright>
    <lastBuildDate>Mon, 01 Jan 0001 00:00:00 +0000</lastBuildDate>
    <atom:link href="http://localhost:1313/solidworks-macros/01-general---solidworks-functions/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>VBA In Solidworks</title>
      <link>http://localhost:1313/Solidworks-macro-guide/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/Solidworks-macro-guide/</guid>
      <description>&lt;p&gt;&lt;em&gt;Solidworks&lt;/em&gt; provides us two methods for open Visual Basic for Application.&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;Menu based method&lt;/li&gt;&#xA;&lt;li&gt;Toolbar method&lt;/li&gt;&#xA;&lt;/ol&gt;&#xA;&lt;p&gt;Please see below video for visual details.&lt;/p&gt;</description>
    </item>
    <item>
      <title>Solidworks Macro - Open new Part document</title>
      <link>http://localhost:1313/solidworks-macros/open-new-document/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/solidworks-macros/open-new-document/</guid>
      <description>&lt;p&gt;As the title suggested, in this post, we open new document &lt;strong&gt;from&lt;/strong&gt; &lt;em&gt;Solidworks VBA macros&lt;/em&gt;.&lt;/p&gt;&#xA;&lt;p&gt;Also we &lt;em&gt;understand&lt;/em&gt; each and every line of written code. So that you can understand why we written those lines and get some knowledge about how to write macro properly.&lt;/p&gt;</description>
    </item>
    <item>
      <title>Solidworks Macro - Open Assembly and Drawing document</title>
      <link>http://localhost:1313/solidworks-macros/open-assembly-and-drawing/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/solidworks-macros/open-assembly-and-drawing/</guid>
      <description>&lt;p&gt;In this post, we see how to open following documents with &lt;em&gt;Solidworks VBA macro&lt;/em&gt;:&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;&#xA;&lt;p&gt;&lt;em&gt;Solidworks Assembly document&lt;/em&gt;&lt;/p&gt;&#xA;&lt;/li&gt;&#xA;&lt;li&gt;&#xA;&lt;p&gt;&lt;em&gt;Solidworks Drawing document&lt;/em&gt;&lt;/p&gt;</description>
    </item>
    <item>
      <title>Solidworks Macro - Selection Methods</title>
      <link>http://localhost:1313/solidworks-macros/select-plane-from-tree/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/solidworks-macros/select-plane-from-tree/</guid>
      <description>&lt;p&gt;In this post, we select &lt;strong&gt;Default planes&lt;/strong&gt; with following methods.&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;&#xA;&lt;p&gt;By &lt;code&gt;SelectByID&lt;/code&gt; method From &lt;code&gt;ModelDoc2&lt;/code&gt; Interface.&lt;/p&gt;&#xA;&lt;/li&gt;&#xA;&lt;li&gt;&#xA;&lt;p&gt;By &lt;code&gt;SelectByID2&lt;/code&gt; method From &lt;code&gt;IModelDocExtension&lt;/code&gt; Interface.&lt;/p&gt;</description>
    </item>
    <item>
      <title>Solidworks Macro - Open Saved Documents</title>
      <link>http://localhost:1313/solidworks-macros/open-saved-document/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/solidworks-macros/open-saved-document/</guid>
      <description>&lt;p&gt;In this post, I tell you how to &lt;em&gt;open a saved document&lt;/em&gt; in Solidworks using &lt;em&gt;VBA Macro&lt;/em&gt;.&lt;/p&gt;&#xA;&lt;p&gt;We open document with 2 different methods.&lt;/p&gt;</description>
    </item>
    <item>
      <title>Solidworks Macro - Fix Unit Issue</title>
      <link>http://localhost:1313/solidworks-macros/unit-correction/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      <guid>http://localhost:1313/solidworks-macros/unit-correction/</guid>
      <description>&lt;p&gt;In this post, I tell you about &lt;strong&gt;how to Fix &lt;em&gt;Unit Issue&lt;/em&gt; in Solidworks API from VBA Macros&lt;/strong&gt; in a Sketch.&lt;/p&gt;</description>
    </item>
  </channel>
</rss>
